### ISSUE TITLE
`__esModule` is `true` while no default export provided, breaks interoperability

### ISSUE THREAD

**Issue by sodatea** [terser-js/terser#251] opened 2019-02-02 18:04 UTC
See:
https://github.com/vuejs/vue-cli/issues/3407
https://github.com/webpack-contrib/terser-webpack-plugin/issues/66

A common way to transpile ES module `import` to CommonJS `require`:
```
function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
```

So this change breaks a lot of downstream packages including [terser-webpack-plugin](https://unpkg.com/terser-webpack-plugin@1.2.1/dist/minify.js)

**Comment by jonryser** [comment] 2019-02-02 18:53
Yes, this is breaking code I am involved with (trying to do a 911 hotfix deployment on a Saturday morning).
Terser is a dependency of terser-webpack-plugin which in turn is a dependency of webpack.
We don't have any way to fix the version to a version that is working.

**Comment by carltierney** [comment] 2019-02-02 19:05
Yes this broke our build as well...

**Comment by filipesilva** [comment] 2019-02-02 21:50
Added a fix in https://github.com/terser-js/terser/pull/254.

**Comment by rveitch** [comment] 2019-02-02 22:41
Verified, also causing build issues for us.

**Comment by hamit-zor** [comment] 2019-02-02 22:50
I am punching myself about 4 hours because of this problem! I just could not understand asking myself  "IT WAS WORKING JUST 10 MINS AGO WHY IT DOESN'T NOW!" I just figured out it was something with update. Holy god.

**Comment by hamit-zor** [comment] 2019-02-02 23:05
Verified, I had same build issues.

**Comment by MarkusA380** [comment] 2019-02-03 10:44
I have literally reset my OS yesterday because of this...

**Comment by jackson-** [comment] 2019-02-03 15:32
Does anybody know how to fix this with Heroku? I keep getting this error when pushing to server:

`
js/app.f394d862.js from Terser    
TypeError: Cannot read property 'minify' of undefined at minify (/tmp/build_e50a34b4bba0c5a074e58791acf9717a/node_modules/terser-webpack-plugin/dist/minify.js:175:23)
`

**Comment by sagitsofan** [comment] 2019-02-03 15:49
`npm install terser@3.14` will fix the issue

**Comment by hamit-zor** [comment] 2019-02-03 16:59
> I have literally reset my OS yesterday because of this...

And I spent my 6 hours just to solve that problem, because I was playing with my configuration and I thought I messed up something serious. I just could figure it out after switching to my notebook and try a simple webpack build. It seriously failed again and then I finally decided to come to github page. The problem is google cannot index that fast so you cant find that error if you try to google it.

**Comment by jackson-** [comment] 2019-02-03 17:12
> `npm install terser@3.14` will fix the issue

I tried this and still the same error

**Comment by sagitsofan** [comment] 2019-02-03 17:18
Does this package wriiten under your dev packages? Share your build logs..

**Comment by bdrtsk** [comment] 2019-02-03 18:11
My Nuxt app now broken and I have no idea how to fix it. But now I know that `tenser` exist! Cool. Had no idea what the hack is it. Nice to meet you `tenser`

**Comment by TrySound** [comment] 2019-02-03 18:17
Who uses yarn add this to package.json
```
"resolutions": {
  "terser": "3.14.*"
}
```

**Comment by tetreault** [comment] 2019-02-03 20:13
Another nuxt user reporting in who cannot generate static files due to this error

**Comment by GeekStocks** [comment] 2019-02-04 03:39
I suggest renaming this package `overly-terse`   ;-P

**Comment by bdrtsk** [comment] 2019-02-04 10:23
Just to everyone who is waiting for the fix. Package maintainer is alive and well being, but "he just like default exports" (c) so get deal with that everyone. 

https://twitter.com/swyx/status/1091959223406084096

![screenshot from 2019-02-04 12-07-50](https://user-images.githubusercontent.com/45076741/52202554-77583700-2877-11e9-9c2c-bc32aa52d277.png)

Nice opportunity to became famous. How many people now know about `terser` existence? If you want to became famous, make popular library, then break it and don't fix it. This is how it looks to me, but I can be wrong.

**Comment by rkiranchowdhary** [comment] 2019-02-04 10:46
Is the issue fixed, or what is the timeline?

**Comment by bdrtsk** [comment] 2019-02-04 10:51
@rkiranchowdhary it will not be fixed (well, at least looks like until we beg package author, or Hacker News will write about the genius who broke the web). The maintainer "really like default exports", we need to adapt and move on. Don't be like "Mimimi, 2 days without a fix how can you do that?!?!". It will achieve nothing besides that maintainers get sick of such comments, the "community" (though the majority didn't do anything) and open source in general (c)

**Comment by Jessidhia** [comment] 2019-02-04 10:54
Not sure if a public lynching is the right approach here. You're even quoting out of context as he is not talking about JavaScript but about a hobby(?) language he's designing.

At any rate, this refactoring looks perfectly acceptable to me. It _is_ the theoretically correct way to export this module. Well, almost, it's missing a `.mjs` export that is an actual ES module; right now it's just an UMD bundle that presents itself as a babelmodule.

*However*, the commit that introduced the change did it fully aware it is a breaking change (it includes dropping Node v4 support, not just this), and semver says that breaking changes should be a major bump.

Terser 3.16 should be unpublished and re-published as Terser 4.0 instead.

**Comment by pedrofurtado** [comment] 2019-02-04 10:57
@fabiosantoscode Any news about this issue?

**Comment by bdrtsk** [comment] 2019-02-04 11:08
@Jessidhia I absolutely don't care how exactly it was refactor and what exports it is using. I care about how author handles issues that aware **whole** webpack ecosystem. Thousands of apps not working, thousands of human hours will be wasted to found the fix. Nothing works, from `create-react-app` to Nuxt and Next.js. Instead of not being egoistical and make compromise with thousands of people paralyzed from work right now, author speaking on Twitter that he likes it and we should change his mind about that damn exports.

**Comment by Jaid** [comment] 2019-02-04 11:39
![image](https://user-images.githubusercontent.com/6216144/52206214-d028cf00-2879-11e9-980d-0c9748c224d2.png)

Sounds like it's getting resolved soon. :)

**Comment by TrySound** [comment] 2019-02-04 11:45
@bdrtsk It was off topic. That tweet is not about bug. Don't panic.

**Comment by fabiosantoscode** [comment] 2019-02-04 11:54
Sorry about those tweets. I thought it was a plugin issue not a terser issue. Fixed in 3.16.1

**Comment by manniL** [comment] 2019-02-04 11:55
@fabiosantoscode Ignore all the haters and keep up the good work ❤️

**Closed by fabiosantoscode** 2019-02-04 11:54 UTC

**Comment by jskidd3** [comment] 2019-02-04 11:55
@fabiosantoscode Thanks Fabio! 🤘

**Comment by sr2ds** [comment] 2019-02-04 12:10
The 3.16.1 version dont't work with me on `vue-cli-service build`:

```

js/app.14dac6db.js from Terser
TypeError: Cannot read property 'minify' of undefined
    at minify (/usr/local/lib/node_modules/@vue/cli-service/node_modules/terser-webpack-plugin/dist/minify.js:175:23)
    at module.exports (/usr/local/lib/node_modules/@vue/cli-service/node_modules/terser-webpack-plugin/dist/worker.js:13:40)
    at handle (/usr/local/lib/node_modules/@vue/cli-service/node_modules/worker-farm/lib/child/index.js:44:8)
    at process.<anonymous> (/usr/local/lib/node_modules/@vue/cli-service/node_modules/worker-farm/lib/child/index.js:51:3)
    at process.emit (events.js:197:13)
    at emit (internal/child_process.js:828:12)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)

```

Does anyone still have a problem?

**Comment by csvan** [comment] 2019-02-04 13:05
Wow, that escalated quickly...thanks for the fix @fabiosantoscode, sorry you had to take some rage for it.

**Comment by edingroot** [comment] 2019-02-04 16:07
@sr2ds Did you remove package-lock.json and run `npm install` again after modifying package.json?
It works for me!

**Comment by samboylett** [comment] 2019-02-04 16:34
I removed the terser declaration from my yarn.lock, and did `rm -rf node_modules/terser && yarn install`. It is now working for me (version is on 3.16.1)

Thanks @fabiosantoscode !
