### ISSUE TITLE
Non-deterministic output for a fixed input

### ISSUE THREAD

**Issue by jakub-g** [terser-js/terser#139] opened 2018-10-24 09:54 UTC
Type: feature request

We're using terser through webpack 4 (previously uglify2 through webpack 3). We're analyzing the chunks when they go to production and we've noticed that the minified output of some chunks is not always the same, even if the input was the same. In other words, the build output is non-deterministic.

This is because variable renaming seems to be somehow done in non-deterministic way.

Example 1
![image](https://user-images.githubusercontent.com/1437027/47422252-7dbc1a80-d782-11e8-8f5b-a874c4822b95.png)

Example 2
![image](https://user-images.githubusercontent.com/1437027/47422269-86145580-d782-11e8-8c1b-d7513e638f1d.png)

As a consequence, **this breaks long term caching**: after a rebuild from same input, I get new file contents, new `contenthash`, the webpack `manifest` entry for a given chunk has to be updated etc. - the domino effect.

As I said, this is something that has been happening for quite a while (not a regression) both with uglify2 and terser.
I'm not sure if there's some webpack involvement that plays a role here, or if it's a pure uglify/terser issue.

Was there ever an issue reported like that for uglify?
Is there something about minification process that might make it non-deterministic? Perhaps multithreading?

**Comment by kzc** [comment] 2018-10-24 16:11
Terser is 100% deterministic given a certain input. File your bug with Webpack.

Follow the Issue template.
```
    Complete valid ECMAScript code exhibiting the issue with
    `terser` alone - without third party tools or libraries.
    Ideally the input should be as small as possible.
    Code must be in text form - not a screen cap.
    Post a link to a gist if necessary.

    Issues without a reproducible test case will be closed
```

**Comment by kzc** [comment] 2018-10-24 16:50
If you search webpack issues for "deterministic chunks" you will find this open bug ticket: https://github.com/webpack/webpack/issues/4913

**Comment by fabiosantoscode** [comment] 2018-10-24 18:10
Closing until proof that terser is the cause is given.

**Closed by fabiosantoscode** 2018-10-24 18:10 UTC

**Comment by jakub-g** [comment] 2018-10-25 10:15
Hello,

there's been some webpack issues around deterministic chunks (like the one that @kzc linked) but they are coming from different problems (non-deterministic chunk IDs, non-deterministic order of chunks within a file etc.) and we've got those covered already.

I will try to dig into it and provide a minimum working example when I have some time.
