### ISSUE TITLE
Possible breaking change on recent version released

### ISSUE THREAD

**Issue by andresg747** [terser-js/terser#252] opened 2019-02-02 18:13 UTC
**Bug report**

I'm getting **TypeError: Cannot read property 'minify' of undefined** errors on build. 

Details on https://github.com/zeit/next.js/issues/6194

Is it possible that the most recent version of terser released 2 hours ago is related to that issue?

Thanks in advance!

### UPDATE
The fix is being addressed [here](https://github.com/terser-js/terser/pull/254).
Meanwhile, if you cannot wait for an official release with the patch, there is a suggested workaround: 
https://github.com/vuejs/vue-cli/issues/3407#issuecomment-459985313

**Comment by sodatea** [comment] 2019-02-02 18:16
See https://github.com/terser-js/terser/issues/251

**Comment by hamit-zor** [comment] 2019-02-02 23:01
Yes, I was playing with some of the configuration and I thought I messed them up, trying to solve this problem about 5 hours. I just figured out it was related to a new update.

**Comment by mrmckeb** [comment] 2019-02-03 15:11
This is also affecting Create React App. See https://github.com/facebook/create-react-app/issues/6334.

**Comment by TrySound** [comment] 2019-02-03 15:50
@mrmckeb It's [terser-webpack-plugin](https://github.com/webpack-contrib/terser-webpack-plugin) problem. They imported default with interop from the package with potential named exports.

**Comment by mrmckeb** [comment] 2019-02-03 15:59
Thanks @TrySound, I'll chase them up.

**Comment by BuddhiAbeyratne** [comment] 2019-02-03 23:17
FYI Issue also effects Nuxt 
https://github.com/nuxt/nuxt.js/issues/4931

**Comment by vladimiry** [comment] 2019-02-04 04:33
Is not this duplicate of https://github.com/terser-js/terser/issues/251?

> @mrmckeb It's terser-webpack-plugin problem. They imported default with interop from the package with potential named exports.

It would be terser-webpack-plugin's problem if that would be a v4 terser release, but it's v3.16.0. So it's terser's problem as the change is breaking.

**Comment by fabiosantoscode** [comment] 2019-02-04 11:54
Thanks for the report. Fixed in 3.16.1

**Closed by fabiosantoscode** 2019-02-04 11:54 UTC
