### ISSUE TITLE
Passing an empty mangle properties object results in runtime error of output js

### ISSUE THREAD

**Issue by GevatterGaul** [terser-js/terser#181] opened 2018-11-28 12:47 UTC
**Bug report or Feature request?**

Bug report

**Version (complete output of `terser -V`)**

terser 3.10.12

**Complete CLI command or `minify()` options used**

The webpack options are:
```javascript
optimization: {
    minimize: true,
    minimizer: [
      new TerserPlugin({
        cache: false,
        terserOptions: {
          keep_classnames: true,
          keep_fnames: true,
          // will not work like this
          mangle: { properties: {} }
          // without the properties option, it will work
          // mangle: {}
        }
      })
    ]
  }
```
Please see this demo repo: https://github.com/GevatterGaul/tersermangleissue

**`terser` input**

When passing an empty object as properties to the mangle options, the resulting js will produce a runtime error. When we remove the properties object from the mangle options, the resulting js will run fine.

The problem occures when using terser as plugin for webpack with a react app. 

Please see this repo for an example of the error: https://github.com/GevatterGaul/tersermangleissue

**`terser` output or error**

The resulting terser minified code will produce the runtime error below.

```
main.js?155b3eed8bf522b13f16:22 Uncaught Error: Minified React error #96; visit https://reactjs.org/docs/error-decoder.html?invariant=96&args[]=Il for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at ca (main.js?155b3eed8bf522b13f16:22)
    at t (main.js?155b3eed8bf522b13f16:22)
    at oa (main.js?155b3eed8bf522b13f16:22)
    at Object.Wn (main.js?155b3eed8bf522b13f16:22)
    at Object.<anonymous> (main.js?155b3eed8bf522b13f16:22)
    at __webpack_require__ (main.js?155b3eed8bf522b13f16:1)
    at Object.<anonymous> (main.js?155b3eed8bf522b13f16:6)
    at __webpack_require__ (main.js?155b3eed8bf522b13f16:1)
    at Object.<anonymous> (main.js?155b3eed8bf522b13f16:30)
    at __webpack_require__ (main.js?155b3eed8bf522b13f16:1)
```

**Expected result**

We expect the resulting js to run without issues, as it does when removing the properties parameter from the mangle options.

**Comment by kzc** [comment] 2018-11-28 23:33
There's a reason why property mangling is not enabled by default. It requires detailed knowledge of all the code and libraries used in each application and usually a great deal of custom configuration and testing. It is not recommended for novice use:

* https://github.com/terser-js/terser#cli-mangling-property-names---mangle-props
* https://github.com/terser-js/terser#mangling-unquoted-names---mangle-props-keep_quoted
* https://github.com/terser-js/terser#debugging-property-name-mangling
* https://github.com/terser-js/terser#mangle-properties-options

Also read up on the use of `nameCache`, a.k.a. `--name-cache`, as it pertains to `mangle` and `mangle` `properties`. The Terser `nameCache` is not well supported by Terser wrappers such as Webpack and Rollup and requires writing custom code.

* https://github.com/terser-js/terser#api-reference

**Comment by fabiosantoscode** [comment] 2018-12-02 16:50
Closing until a non-third-party example is given

**Closed by fabiosantoscode** 2018-12-02 16:50 UTC

**Comment by damianobarbati** [comment] 2019-09-11 07:50
@GevatterGaul I have the same problem, did you find the cause?
